sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: SBgA3PRPbqzxKszYJ3AdLnPyAIfR02+KT3unkgSWEJSbJk6o58rVp7AFVU9KaCUTyn1FMUv5wZHfNgEsbNG6XWVc+LUoTWAqz7vi1dJREjfAjszgHbtoSJ9UgY8aGrXV27SI80c9pbB7l0EDGj84EHOhMrY5NBUmbupzpSIDLPKo5SEg3h69fIxWIBizk0xOSMZdBK5k9fOygH8GaWaMzHw3hj4Cz9xh/jqLQCCMWrbM7Pj+sbJ2jbp1ReSHX2lab2/XMCusvLYlI0YFwmQP4eaURcD8Q6lZr4uptFsKffx0lmRfaEyR4Wql/XBzUoPoHyF5cNJZK5DosIkSGFqxktlkmPm/q7RFiPtDL4A88Q9IjRGXnMFlfcqp1WNMtdone4I4miDTcZWblCPDgTcW1W8J6Heu8D0KWUd3hh8MPBMnWYXglZKECoFiPH7d256N7Da/kOpfDLsPfmshnilv9AbaBMpj850nUAwDJOErk0X7UFvGM95HcLZthudVdZnReh5mo5hWwkaBu9uRqtY/5sNtz4HXAxw3EJeVWs0CKc+849uFJtCXWjjCe3A3T2Q+s7faqKSNwl/OxK8HpmRMhV7nx2GwPVq/VlzmdBFXQu+tk2QFbpsIUEls4TJg4tGcgvQT3MDZh75dhL7x5GF+a/g9EKtBtr8D0PbbYD+fJ+A=
  - secure: umdqx7IrcKa5fcX9P/1QwZIrZCbF1NESHZNGEpdofh5e72Cb30OquN0I4wxFybZP5YRL6AYuWKFocD6hgeZTTjcKn6CZtBRTW2TFWewsVhTzZSlcsygghxd7eBgg+UxabVHRq9FDs+2P3Hnmp8T4GtUBKrwPljqbhSHI5hMKibHXbIReTv/EWW6tIs23TfN7LPlisy8HTUkkJO1tPL5qUjPNIQ0XDPMWELgvxlJY82Awg2C5OX7Ew3bjMEntKpOdiM/fQsBLbSXQStuzxpCQx4472CG7FitIGSwuidw/F87FO6PEW6ap73fmm6MwIYdDrdnKl1iBuuS4uHmN5Hq1Qzx8Mwcn+W9nLMRVBrDRCA/F6xTT5202lHnQ5hTtKbt1tH/UUXyLXpBT2lXZhPkVX7edNNmFvRREpO04KRu29ys50CZZQCGGg2jCP0aaKV+Cvq4BKM+CY4TKQx4x0moylCtC8Lw3t3+XyYdi6ddiAMzB620WVChNKlNCV6RCe8w3fZcp/hH33j+LrCaOv1bkqGIwwVLz3lOaZMHv5xENl1u7cgtHlY4AD8cbOGY4E0aEEnMFQyUdfM4bHN8HRowfCDOjYvLtVBCgKOB0aJ556ZFd9+haND/MW+CyTkOA7kKVP0fOBUpp6d84QTKTOancRm3WAHbKugyFY66peHFnVjM=
  - secure: R51OWKWUy9+675rTaSA26J50tSMHxlOt6UtAQMQISDpWrP7+vPKU3Ekxh1rLldVXxIfPSSKI3YL5toyM+eqvl0z2NaSY2Orqa9mPofVMKwxJNlGyPKGI0lpl6bRV4BZQuTJBUOT7BUYRs+Vh5bMKXjN8ICb7x/OuQWpqUvs0v1RbG7navD9GeZBoHsW2Wck8qhZKGmFPhtlOM6uzVpFfRTTjSJsXKEOSJ2g+bxvE9demEzVCP7eOWECw8YEJiuKinmNIJhKjFpwOLuxhEJP4EqcY9Rq1nCo/NZMj1J/qkCqJ9ozK8ezme0HuPttQ/z5Obe/gj9QTaj1agwRnPviLDu9W3f23oaBLHwsHOljJFQ0COPtE8qsvPiuxXSp9DUVU9/3CVQodO+d81TQmEHSx//4H4OIEuabHAzIJd+Z/64UU2S9OpAZ0ECEk1+OG6dUk3WP++H/EcbwqdojHI2YqcHNWILgRxXp4Ad+eY1Ff+67q/TgiL7y4o6ze2uQh+oVEtl8DlJb4EwQH8JCJ0BUa2JQW6bU073R1NQ2ceTys3zFkyiWKzYPqDvjangznQ0YBH5NEtrunZWv74Wfvpx3XHrZpV++RsgbkVfuLjtunXZvs/pHmP2nwXVGgeXsG4cH6wbdyLIT6QLwkL9ffhsmhejbZye73u+5sHP575qKNN0Y=
  - secure: aaTwuY57VJftxn2jE8+F3TnKoVqON36bGV8za3kSCwo2RTWdgVftbCI4FkWO269Kh6C+IlBhaaS5NlcYh92K6LAKxDVfyWsOpdcUcGD+9EXHUR42t17Na2X6zSSlfBHy8V+oW+7FFmrkWsEue+B2NQjiRLyjG8/P97n54A+Ysm7/gL7lxLt3YSeX94XJ8O7Kr9rT2+/R1uzg8L1DKd2uhdNYq0SPI3t6aS/VIVuN0Dbc/mDaKeayCIB06h1FXxZoaVzs9s56pX4WHtc/hknqYamv69ivONV3sCsdiwLBXnAC24RNm5qZwun7ovP3Wn6KZmltxBm3OR3J5OMQAJEzcjNA95Nsv9cNUBy5IsJ08FW7dEQZtC1Ug84rGab7cGjOoqnaWkleZh6+PlT4+6QWZx97unnYYGzbh30zoPSZ7m12YJyACS6vRaN2t3ozONmreCB7LuafFs5SaTcxBl7/IalkbW4W83SuPH44w+knqVqkl6wev/NxaycfVOrnfhe5FbleFJwuPPZUyFOPuZLaLFRqkyii7GbMuVYeA5ZnCBunksVIIii2Uo1ILQtFx+buEekPXwyo4xqwnFONkzI41QL2Vv7B/bRw+oEb7zMxlK1L3LCisNnqPVg+smlhgUerJW2MsKkjleJ4u+EikAU9s3adhZCKSzJzvHKnOS1D7nA=
